//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressYourself.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressYourself.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Status: Connected.
        /// </summary>
        internal static string KinectConnected {
            get {
                return ResourceManager.GetString("KinectConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Status: Disconnected.
        /// </summary>
        internal static string KinectDisconnected {
            get {
                return ResourceManager.GetString("KinectDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Status: Unpowered.
        /// </summary>
        internal static string KinectNoPower {
            get {
                return ResourceManager.GetString("KinectNoPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Status: Not Ready.
        /// </summary>
        internal static string KinectNotReady {
            get {
                return ResourceManager.GetString("KinectNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Status: No ready device found.
        /// </summary>
        internal static string KinectUnavailable {
            get {
                return ResourceManager.GetString("KinectUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect Status: Waiting….
        /// </summary>
        internal static string KinectWaiting {
            get {
                return ResourceManager.GetString("KinectWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5204.
        /// </summary>
        internal static string NetworkPort {
            get {
                return ResourceManager.GetString("NetworkPort", resourceCulture);
            }
        }
    }
}
